version: '3.8'

services:
  app:
    build:
      context: .
    container_name: Apispringboot
    ports:
      - "8080:8085"
    networks:
      tiendaRed:
        ipv4_address: 192.168.0.12

networks:
  tiendaRed:
    external: true
    name: tienda-red


      